// Mocks generated by Mockito 5.4.6 from annotations
// in darkfeed/test/helpers/mock_pixelfed_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:darkfeed/models/post.dart' as _i2;
import 'package:darkfeed/services/pixelfed_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserAccount_0 extends _i1.SmartFake implements _i2.UserAccount {
  _FakeUserAccount_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePost_1 extends _i1.SmartFake implements _i2.Post {
  _FakePost_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PixelfedService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPixelfedService extends _i1.Mock implements _i3.PixelfedService {
  MockPixelfedService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Post>> getHomeTimeline({
    String? maxId,
    String? sinceId,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeTimeline, [], {
              #maxId: maxId,
              #sinceId: sinceId,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
          )
          as _i4.Future<List<_i2.Post>>);

  @override
  _i4.Future<_i2.UserAccount> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.UserAccount>.value(
              _FakeUserAccount_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i4.Future<_i2.UserAccount>);

  @override
  _i4.Future<_i2.Post> likePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [postId]),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_1(this, Invocation.method(#likePost, [postId])),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<_i2.Post> unlikePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePost, [postId]),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_1(this, Invocation.method(#unlikePost, [postId])),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<_i2.Post> repostPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#repostPost, [postId]),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_1(this, Invocation.method(#repostPost, [postId])),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<_i2.Post> unrepostPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unrepostPost, [postId]),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_1(this, Invocation.method(#unrepostPost, [postId])),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<List<_i2.Comment>> getComments(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId]),
            returnValue: _i4.Future<List<_i2.Comment>>.value(<_i2.Comment>[]),
          )
          as _i4.Future<List<_i2.Comment>>);

  @override
  _i4.Future<_i2.UserAccount> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i2.UserAccount>.value(
              _FakeUserAccount_0(
                this,
                Invocation.method(#getUserProfile, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.UserAccount>);

  @override
  _i4.Future<List<_i2.Post>> getUserPosts({
    required String? userId,
    String? maxId,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPosts, [], {
              #userId: userId,
              #maxId: maxId,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
          )
          as _i4.Future<List<_i2.Post>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
