// Mocks generated by Mockito 5.4.6 from annotations
// in darkfeed/test/helpers/mock_window_manager.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i2;

import 'package:darkfeed/services/window_manager_interface.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:window_manager/window_manager.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSize_0 extends _i1.SmartFake implements _i2.Size {
  _FakeSize_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WindowManagerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockWindowManagerInterface extends _i1.Mock
    implements _i3.WindowManagerInterface {
  MockWindowManagerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> waitUntilReadyToShow(
    _i5.WindowOptions? options,
    _i2.VoidCallback? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#waitUntilReadyToShow, [options, callback]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> maximize() =>
      (super.noSuchMethod(
            Invocation.method(#maximize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unmaximize() =>
      (super.noSuchMethod(
            Invocation.method(#unmaximize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSize(_i2.Size? size, {bool? animate = false}) =>
      (super.noSuchMethod(
            Invocation.method(#setSize, [size], {#animate: animate}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Size> getSize() =>
      (super.noSuchMethod(
            Invocation.method(#getSize, []),
            returnValue: _i4.Future<_i2.Size>.value(
              _FakeSize_0(this, Invocation.method(#getSize, [])),
            ),
          )
          as _i4.Future<_i2.Size>);

  @override
  _i4.Future<bool> isMaximized() =>
      (super.noSuchMethod(
            Invocation.method(#isMaximized, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> center({bool? animate = false}) =>
      (super.noSuchMethod(
            Invocation.method(#center, [], {#animate: animate}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> show({bool? inactive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#show, [], {#inactive: inactive}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.WindowListener? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.WindowListener? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
